//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktury
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktury()
        {
            this.Rozliczenia = new HashSet<Rozliczenia>();
        }
    
        public int Id { get; set; }
        public string NrFaktury { get; set; }
        public System.DateTime DataFaktury { get; set; }
        public int IdWykonawcy { get; set; }
        public int IdZlecenia { get; set; }
        public Nullable<decimal> Kwota { get; set; }
    
        public virtual Wykonawcy Wykonawcy { get; set; }
        public virtual Zlecenia Zlecenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rozliczenia> Rozliczenia { get; set; }
    }
}
