//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formy()
        {
            this.FormyMaszyny = new HashSet<FormyMaszyny>();
            this.Indeksy = new HashSet<Indeksy>();
        }
    
        public int Id { get; set; }
        public string KodFormy { get; set; }
        public string MaszynaDedykowana { get; set; }
        public string Lokalizacja { get; set; }
        public Nullable<decimal> CzasCyklu { get; set; }
        public Nullable<decimal> IloscGniazd { get; set; }
        public Nullable<int> IdMaszyny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormyMaszyny> FormyMaszyny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indeksy> Indeksy { get; set; }
        public virtual Maszyny Maszyny { get; set; }
    }
}
