//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormyMaszyny
    {
        public int Id { get; set; }
        public int IdFormy { get; set; }
        public int IdMaszyny { get; set; }
    
        public virtual Formy Formy { get; set; }
        public virtual Maszyny Maszyny { get; set; }
    }
}
