//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndeksyParametry
    {
        public int IdIndeksu { get; set; }
        public Nullable<decimal> WagaWtryskuBrutto_g { get; set; }
        public Nullable<decimal> WagaWtryskuNetto_g { get; set; }
        public Nullable<int> NormaCzasCyklu_s { get; set; }
        public Nullable<int> KrotnoscFormy { get; set; }
        public Nullable<bool> CzyWlewek { get; set; }
    
        public virtual Indeksy Indeksy { get; set; }
    }
}
