//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndeksBOM
    {
        public int IdBOM { get; set; }
        public int IdIndeksu { get; set; }
        public int IdMaterialu { get; set; }
        public decimal Ilosc { get; set; }
        public decimal UdzialProcentowy { get; set; }
        public string KodIndeksu { get; set; }
        public Nullable<System.DateTime> DataUtworzenia { get; set; }
    
        public virtual Indeksy Indeksy { get; set; }
        public virtual Materialy Materialy { get; set; }
    }
}
