//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indeksy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indeksy()
        {
            this.IndeksBOM = new HashSet<IndeksBOM>();
            this.Zlecenia = new HashSet<Zlecenia>();
            this.Rozliczenia = new HashSet<Rozliczenia>();
        }
    
        public int Id { get; set; }
        public string KodIndeksu { get; set; }
        public string Rodzina { get; set; }
        public string Opis { get; set; }
        public Nullable<int> IdFormy { get; set; }
        public bool PracaAutomatyczna { get; set; }
        public string KodFormy { get; set; }
        public Nullable<int> IdGrupa { get; set; }
        public string GrupaWstawki { get; set; }
    
        public virtual Formy Formy { get; set; }
        public virtual GrupyWstawek GrupyWstawek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndeksBOM> IndeksBOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zlecenia> Zlecenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rozliczenia> Rozliczenia { get; set; }
    }
}
