//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndeksBOM
    {
        public int IdBOM { get; set; }
        public string Indeks { get; set; }
        public Nullable<int> IdMaterialu_M1 { get; set; }
        public Nullable<decimal> Ilosc_M1 { get; set; }
        public Nullable<decimal> Udzial_M1 { get; set; }
        public Nullable<int> IdMaterialu_M2 { get; set; }
        public Nullable<decimal> Ilosc_M2 { get; set; }
        public Nullable<decimal> Udzial_M2 { get; set; }
        public Nullable<int> IdMaterialu_M3 { get; set; }
        public Nullable<decimal> Ilosc_M3 { get; set; }
        public Nullable<decimal> Udzial_M3 { get; set; }
        public Nullable<int> IdMaterialu_M4 { get; set; }
        public Nullable<decimal> Ilosc_M4 { get; set; }
        public Nullable<decimal> Udzial_M4 { get; set; }
        public Nullable<int> IdMaterialu_M5 { get; set; }
        public Nullable<decimal> Ilosc_M5 { get; set; }
        public Nullable<decimal> Udzial_M5 { get; set; }
        public Nullable<int> IdMaterialu_M6 { get; set; }
        public Nullable<decimal> Ilosc_M6 { get; set; }
        public Nullable<decimal> Udzial_M6 { get; set; }
        public Nullable<int> IdIndeksu { get; set; }
    
        public virtual Indeksy Indeksy { get; set; }
        public virtual Materialy Materialy { get; set; }
        public virtual Materialy Materialy1 { get; set; }
        public virtual Materialy Materialy2 { get; set; }
        public virtual Materialy Materialy3 { get; set; }
        public virtual Materialy Materialy4 { get; set; }
        public virtual Materialy Materialy5 { get; set; }
    }
}
