//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KonfiguracjaSystemu
    {
        public string Klucz { get; set; }
        public Nullable<decimal> Wartosc { get; set; }
        public string Opis { get; set; }
    }
}
