//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KosztyMaterialowe
    {
        public int IdMaterialu { get; set; }
        public decimal CenaJednostkowa { get; set; }
        public System.DateTime DataModyfikacji { get; set; }
        public string KodMaterialu { get; set; }
        public string Opis { get; set; }
        public string JednostkaMiary { get; set; }
        public int IdKosztuMaterialowego { get; set; }
        public System.DateTime DataUtworzenia { get; set; }
        public bool Aktywne { get; set; }
    
        public virtual Materialy Materialy { get; set; }
    }
}
