//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogistykaWykonawcow
    {
        public int IdWykonawcy { get; set; }
        public Nullable<int> DystansKM { get; set; }
        public Nullable<decimal> KosztZaKM_Default { get; set; }
    
        public virtual Wykonawcy Wykonawcy { get; set; }
    }
}
