//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materialy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materialy()
        {
            this.KosztyMaterialowe = new HashSet<KosztyMaterialowe>();
            this.ZlecenieBOM = new HashSet<ZlecenieBOM>();
            this.IndeksBOM = new HashSet<IndeksBOM>();
        }
    
        public int Id { get; set; }
        public string KodMaterialu { get; set; }
        public string Nazwa { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public Nullable<int> Jednostka { get; set; }
        public string RodzajMaterialu { get; set; }
        public string KodJednostki { get; set; }
    
        public virtual Jednostki Jednostki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KosztyMaterialowe> KosztyMaterialowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZlecenieBOM> ZlecenieBOM { get; set; }
        public virtual RodzajeMaterialow RodzajeMaterialow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndeksBOM> IndeksBOM { get; set; }
    }
}
