//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVVMFirmaEntities13 : DbContext
    {
        public MVVMFirmaEntities13()
            : base("name=MVVMFirmaEntities13")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Faktury> Faktury { get; set; }
        public virtual DbSet<Formy> Formy { get; set; }
        public virtual DbSet<FormyMaszyny> FormyMaszyny { get; set; }
        public virtual DbSet<GrupyWstawek> GrupyWstawek { get; set; }
        public virtual DbSet<IndeksBOM> IndeksBOM { get; set; }
        public virtual DbSet<Indeksy> Indeksy { get; set; }
        public virtual DbSet<Jednostki> Jednostki { get; set; }
        public virtual DbSet<KosztyMaterialowe> KosztyMaterialowe { get; set; }
        public virtual DbSet<KosztyOperacyjne> KosztyOperacyjne { get; set; }
        public virtual DbSet<Kraje> Kraje { get; set; }
        public virtual DbSet<Maszyny> Maszyny { get; set; }
        public virtual DbSet<Materialy> Materialy { get; set; }
        public virtual DbSet<Rozliczenia> Rozliczenia { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Wstawki> Wstawki { get; set; }
        public virtual DbSet<Wykonawcy> Wykonawcy { get; set; }
        public virtual DbSet<Zlecenia> Zlecenia { get; set; }
        public virtual DbSet<ZlecenieBOM> ZlecenieBOM { get; set; }
    }
}
