//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rozliczenia
    {
        public int Id { get; set; }
        public Nullable<int> IdFaktury { get; set; }
        public int IdZlecenia { get; set; }
        public string NrZlecenia { get; set; }
        public int IdIndeksu { get; set; }
        public int IloscZlecona { get; set; }
        public System.DateTime DataWystawienia { get; set; }
        public int IloscWykonana { get; set; }
        public decimal Scrap { get; set; }
        public Nullable<decimal> TKWPlan { get; set; }
        public Nullable<decimal> TKWReal { get; set; }
        public Nullable<System.DateTime> DataRozliczenia { get; set; }
        public Nullable<int> IloscZafakturowana { get; set; }
        public Nullable<decimal> Kwota { get; set; }
        public int IdWykonawcy { get; set; }
        public string NazwaWykonawcy { get; set; }
        public Nullable<decimal> MaterialOdzyskany { get; set; }
        public Nullable<decimal> MaterialUtylizacja { get; set; }
        public Nullable<decimal> RzeczCzasCyklu { get; set; }
        public string Status { get; set; }
    
        public virtual Faktury Faktury { get; set; }
        public virtual Indeksy Indeksy { get; set; }
        public virtual Wykonawcy Wykonawcy { get; set; }
        public virtual Zlecenia Zlecenia { get; set; }
    }
}
