//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wstawki
    {
        public int Id { get; set; }
        public string KodWstawki { get; set; }
        public string KodIndeksuWyrobu { get; set; }
        public string GrupaWstawki { get; set; }
        public Nullable<int> IdGrupa { get; set; }
    
        public virtual GrupyWstawek GrupyWstawek { get; set; }
    }
}
