//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wykonawcy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wykonawcy()
        {
            this.Faktury = new HashSet<Faktury>();
            this.Rozliczenia = new HashSet<Rozliczenia>();
            this.Zlecenia = new HashSet<Zlecenia>();
        }
    
        public int Id { get; set; }
        public string NrWykonawcy { get; set; }
        public string Nazwa { get; set; }
        public string NIP { get; set; }
        public string Telefon { get; set; }
        public string Kraj { get; set; }
        public string Miasto { get; set; }
        public string KodPocztowy { get; set; }
        public string Ulica { get; set; }
        public string NrDomu { get; set; }
        public Nullable<int> IdKraju { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury { get; set; }
        public virtual Kraje Kraje { get; set; }
        public virtual LogistykaWykonawcow LogistykaWykonawcow { get; set; }
        public virtual ParametryLogistyczne ParametryLogistyczne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rozliczenia> Rozliczenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zlecenia> Zlecenia { get; set; }
    }
}
