//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZlecenieBOM
    {
        public int Id { get; set; }
        public int IdZlecenia { get; set; }
        public int IdMaterialu { get; set; }
        public decimal Ilosc { get; set; }
    
        public virtual Materialy Materialy { get; set; }
        public virtual Zlecenia Zlecenia { get; set; }
    }
}
