//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zlecenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zlecenia()
        {
            this.Faktury = new HashSet<Faktury>();
            this.KosztyOperacyjne = new HashSet<KosztyOperacyjne>();
            this.Rozliczenia = new HashSet<Rozliczenia>();
            this.ZlecenieBOM = new HashSet<ZlecenieBOM>();
        }
    
        public int Id { get; set; }
        public string NrZlecenia { get; set; }
        public System.DateTime DataZlecenia { get; set; }
        public int IdWykonawcy { get; set; }
        public int IdIndeksu { get; set; }
        public int Ilosc { get; set; }
        public string Uwagi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktury> Faktury { get; set; }
        public virtual Indeksy Indeksy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KosztyOperacyjne> KosztyOperacyjne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rozliczenia> Rozliczenia { get; set; }
        public virtual Wykonawcy Wykonawcy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZlecenieBOM> ZlecenieBOM { get; set; }
    }
}
